### ISSUE TITLE
Updated 'ru_ru' translation from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by BrickerMoss** [Yirmiri/Excessive-Building#1]
'ru_ru' lang file for current version of EB: [ru_ru.json](https://github.com/user-attachments/files/16520721/ru_ru.json)

**Comment by Yirmiri** [comment]
Thank you :), next time though is it okay if you open this via a pull request?
I got the file so no need to for this time.

**Comment by BrickerMoss** [comment]
> Thank you :), next time though is it okay if you open this via a pull request? I got the file so no need to for this time.

Oh yeah, sure! Sorry, i tried to send it through pull request, but i just didn't figure it out :'(
