### ISSUE TITLE
Crafting Table and Bookshelf recipes broken

### ISSUE THREAD

**Issue by Zartrix** [Yirmiri/Excessive-Building#11]
Probably related to #10 
Some Crafting Tables and Bookshelves recipes result in Oak Crafting Table/Bookshelf.
I'm on Fabric 1.20.1 using Excessive Building 3.2.6
![](https://github.com/user-attachments/assets/6b7e7fab-5e9a-4478-b39d-c5a34eae051e)
![](https://github.com/user-attachments/assets/bc9eecab-c4ad-4e57-98c4-40815897d34e)

**Comment by Yirmiri** [comment]
🥴Will look into this

**Comment by Yirmiri** [comment]
This has been fixed in a version that is now uploading to mod sites, thanks :P
