### ISSUE TITLE
Can't craft vanilla Bookshelf or Crafting Table

### ISSUE THREAD

**Issue by MocuryMoto** [Yirmiri/Excessive-Building#13]
The recipes for all the custom crafting tables/bookshelves work fine, but when trying to craft with oak or a modded wood type without a custom result, nothing happens. Looked through EMI and the bookshelf recipe is completely gone while the crafting table recipe is, uh...
![image](https://github.com/user-attachments/assets/2859f743-9b7f-4009-b0cd-b051459fc07c)
...well, it's definitely not what it should be.
Fabric 1.20.1 on Excessive Building 3.2.8. Bookshelves had this problem previously but the Crafting Table part is definitely new to this version.

**Comment by Yirmiri** [comment]
Will be fixed in an upcoming version 3.2.9 *should be out soon..

**Comment by Yirmiri** [comment]
Version is now uploading to CF and Modrinth, thanks for reporting.
