### ISSUE TITLE
Some recipes not available

### ISSUE THREAD

**Issue by Sgee-plays** [Yirmiri/Excessive-Building#14]
I'm in a survival world and was planning on using cobblestone brick walls for a build, but when I tried crafting them in my stone cutter it didn't show up. Then I tried putting in the standard wall recipe in a crafting table, it also didn't work
![image](https://github.com/user-attachments/assets/c3f33700-0a7a-4341-9027-223fb1e294e8)
![image](https://github.com/user-attachments/assets/1a501afb-4550-4dc7-89b4-374660a747cf)
(excuse my UI, that's just a recourse pack.)

**Comment by Sgee-plays** [comment]
I tried JEI, but it didn't show any recipe there.

**Comment by Sgee-plays** [comment]
Turns out, after some testing, this isn't the only item that doesn't show a recipe in JEI. Some others include: cobbled deepslate brick wall (and the mossy version), the mossy cobblestone brick wall, Blackstone brick wall (and the weeping and twisting versions, polished included). Asphalt, all almentra statues. (I assume the last two don't have a recipe and are created otherwise).
What stands out to me is that all of these issues concern the wall variants of new variants of already existing minecraft blocks. Am I just dumb and don't realize that you have to craft them another way, or is this really just an issue?

**Comment by Yirmiri** [comment]
Asphalt is obtained via Mason Villagers at max level and almentra statues are created via the hammer. The rest of the recipes are mistakes on my end and I will fix them soon.

**Comment by Yirmiri** [comment]
These are fixed in an upcoming update ! Thanks for reporting
