### ISSUE TITLE
paintings wont render

### ISSUE THREAD

**Issue by ElfKing94** [Yirmiri/Excessive-Building#18]
hey i found the paintings in creative yet i cant get them to render, am i missing somthing? thanks

**Comment by Yirmiri** [comment]
What version of the mod, mod loader, and game version are you using

**Comment by ElfKing94** [comment]
3.2.9, fabric 1.20.1

**Comment by Yirmiri** [comment]
Thanks, will take a look now

**Comment by Yirmiri** [comment]
This is fixed and will be apart of the next release 3.2.10 (uploading now)

**Comment by ElfKing94** [comment]
wow thanks and good job, only  one thats missing now from what i can tell is the goodiemalk.title or author one (2nd to last i believe next to rebel the dog). they look great! thanks again!
