### ISSUE TITLE
Cobbled Deepslate Bricks recipe conflict

### ISSUE THREAD

**Issue by MQXO** [Yirmiri/Excessive-Building#19]
The cobbled deepslate bricks recipe conflicts with the minecraft:polished_deepslate recipe (i.e. they're both 4 deepslate in a 2x2 grid). Causing a huge waste of cobbled deepslate for me because I'm an idiot and keep forgetting - current workaround is just using a stonecutter but that's much less convenient than just crafting them in your inventory.

Could be intentional, idk?

1.20.1 Fabric v3.2.9 (latest)

**Comment by Yirmiri** [comment]
This is not intentional, will fix asap !

**Comment by Yirmiri** [comment]
This is fixed and will be apart of the next release 3.2.10 (uploading now)
