### ISSUE TITLE
[1.20.1 Forge] Incompatibility with Biomes We've Gone

### ISSUE THREAD

**Issue by ambientNexus** [Yirmiri/Excessive-Building#2]
Reposting this issue here so you can take a look at it. Game crashes when both this mod and BWG are installed upon generating chunks, whether starting a new world or loading into an existing one.
https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/6

**Comment by Yirmiri** [comment]
I apologize but I am no longer supporting Forge Excessive Building at this current time.

**Comment by Yirmiri** [comment]
This issue shouldn't even be here considering this is the Fabric repository
