### ISSUE TITLE
[Bug] Server Console Log Breaks

### ISSUE THREAD

**Issue by NFLD99** [Yirmiri/Excessive-Building#4]
### Issue: Server Console Logs Broken with Mod Installed

**With the mod installed:**
- Console log shows:  
  ```  
  menu.preparingSpawn  
  ```  
- [latest.log](https://github.com/user-attachments/files/16884159/latest.log)

**Without the mod installed:**
- Console log shows:  
  ```  
  Preparing spawn area: 0%  
  ```  
- [latest.log](https://github.com/user-attachments/files/16884184/latest.log)

---

### Environment Details

- **Minecraft Version:** 1.20.1  
- **Modloader:** Fabric  
- **Fabric Loader Version:** 0.16.3  
- **Java Version:** 21  
- **Mod Version:** Excessive Building [Fabric] 1.20.1-2.0.4  

---

**Comment by NFLD99** [comment]
User: [dicedpixels] on The Fabric Project Discord server suggested [Here](https://ptb.discord.com/channels/507304429255393322/895938137778446386/1281115219992645693) that [src/main/resources/resourcepacks/vanilla_retextures/assets/minecraft/lang/en_us.json](https://github.com/Yirmiri/Excessive-Building/blob/main/src%2Fmain%2Fresources%2Fresourcepacks%2Fvanilla_retextures%2Fassets%2Fminecraft%2Flang%2Fen_us.json) is the issue
![RwYADe5FBS](https://github.com/user-attachments/assets/cc007f99-4d97-4b4b-ac9f-88e15f77799b)

**Comment by Yirmiri** [comment]
I recently rewrite the entire mod from the ground up and the given suggestion for the source of this issue is actually ironically the solution to the issue for the latest version of this mod.
I'll look into updating the 1.20.1 version when I get the chance as there are a couple other issues I want to squash first.
In the meantime you can just remove the `en_us.json` file located under `assets/minecraft/lang`

**Comment by NFLD99** [comment]
> I recently rewrite the entire mod from the ground up and the given suggestion for the source of this issue is actually ironically the solution to the issue for the latest version of this mod.
> I'll look into updating the 1.20.1 version when I get the chance as there are a couple other issues I want to squash first.
> In the meantime you can just remove the `en_us.json` file located under `assets/minecraft/lang`

Where do we remove that in our server pack for our modpack? (As of now we have the mod removed fully until we can fix it and be able to be approved by curse forge or it is fixed)

**Comment by Yirmiri** [comment]
You would have to convert the mod jar into a zip and locate and delete the language file under `assets/minecraft/lang`, after which you can convert the zip back into a jar file.
I should have a small patch releasing sometime this week.

**Comment by Yirmiri** [comment]
A new 1.20.1 Excessive Building version is now being approved by CF and Modrinth, it fixes many issues including the lang issue.
